---
version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 050451369651.dkr.ecr.ap-south-1.amazonaws.com
      # $(aws ecr get-login --no-include-email --region us-east1)
      #- REPOSITORY_URI=533267368393.dkr.ecr.eu-central-2.amazonaws.com/fp-staging-backend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg NG_BUILD_CONFIGURATION=$ENV -t $REPOSITORY_URI:latest -f Dockerfile.$SERVICE .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
     # - docker push $REPOSITORY_URI:latest  #docker push to latest won't work with tag immutability set to ON in ECR
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $SERVICE $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
