FROM node:18.16 as build
WORKDIR /app
RUN npm install -g @angular/cli@16.1.4
COPY . .
RUN npm install --force
#RUN ng build
ARG NG_BUILD_CONFIGURATION
RUN ng build --configuration=production
FROM nginx:alpine as runtime
COPY --from=build /app/dist/angular-admin /usr/share/nginx/html
COPY --from=build /app/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
