name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: "pay2nep-prod-stack"
          template: "./cloudformation/template.yaml"
          no-fail-on-empty-changeset: true
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: |
            VpcCidrProd=172.21.0.0/16
            InstanceType=t2.medium
            KeyName=demo-cluster-key
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
